 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package doctorui;

import javax.swing.JOptionPane;

import java.awt.BorderLayout;
import java.awt.Color;
import javafx.scene.chart.Chart;
import org.jfree.chart.*;
import org.jfree.chart.plot.*;
import org.jfree.data.category.DefaultCategoryDataset;


import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.net.URI;
import java.net.URL;
import java.net.URLConnection;
import java.net.URLEncoder;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author roshanantonyarunkumar
 */
public class ClientDataFrame extends javax.swing.JFrame {

    /**
     * Creates new form ClientDataFrame
     */
    
    Client client;
    String username;
    public ClientDataFrame(Client client, String username) {
        initComponents();
        this.client = client;
        this.username=username;
        ClientNameLabel.setText("Client: " + client.getName());
        
        VersionDataLabel.setText("Version: " + client.getVersionID());
        FOVDataLabel.setText("FOV " + client.fov);
        BrightnessDataLabel.setText("Brightness: "+ client.brightness);
        SizeDataLabel.setText("Size: " + client.size);
        Pos_XDataLabel.setText("Pos_X: " + client.pos_x);
        Pos_YDataLabel.setText("Pos_Y: " + client.pos_y);
        Off_XDataLabel.setText("Off_X: " + client.off_x);
        Off_YDataLabel.setText("Off_Y: " + client.off_y);
        
        
        
          
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        UpdateDataPanel = new javax.swing.JPanel();
        BrigthnessLabel = new javax.swing.JLabel();
        BrightnessField = new javax.swing.JTextField();
        FOVField = new javax.swing.JTextField();
        Off_XLabel = new javax.swing.JLabel();
        SizeLabel = new javax.swing.JLabel();
        SizeField = new javax.swing.JTextField();
        Off_YLabel = new javax.swing.JLabel();
        Off_XField = new javax.swing.JTextField();
        Pos_XLabel = new javax.swing.JLabel();
        Pos_YLabel = new javax.swing.JLabel();
        Off_YField = new javax.swing.JTextField();
        Pos_YField = new javax.swing.JTextField();
        Pos_XField = new javax.swing.JTextField();
        UpdateDataButton = new javax.swing.JButton();
        FOVLabel1 = new javax.swing.JLabel();
        NamePanel = new javax.swing.JPanel();
        ClientNameLabel = new javax.swing.JLabel();
        ShowChartButton = new javax.swing.JButton();
        RemoveClientButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        BrightnessDataLabel = new javax.swing.JLabel();
        VersionDataLabel = new javax.swing.JLabel();
        Off_YDataLabel = new javax.swing.JLabel();
        Pos_XDataLabel = new javax.swing.JLabel();
        FOVDataLabel = new javax.swing.JLabel();
        SizeDataLabel = new javax.swing.JLabel();
        Pos_YDataLabel = new javax.swing.JLabel();
        Off_XDataLabel = new javax.swing.JLabel();
        Back = new javax.swing.JButton();
        ChartOption = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 562));
        setSize(new java.awt.Dimension(1000, 562));

        kGradientPanel1.setMinimumSize(new java.awt.Dimension(1000, 562));
        kGradientPanel1.setPreferredSize(new java.awt.Dimension(1000, 562));

        UpdateDataPanel.setBackground(new java.awt.Color(255, 255, 255));

        BrigthnessLabel.setBackground(new java.awt.Color(0, 238, 238));
        BrigthnessLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BrigthnessLabel.setForeground(new java.awt.Color(12, 91, 160));
        BrigthnessLabel.setText("BRIGHTNESS");

        BrightnessField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BrightnessField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        BrightnessField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrightnessFieldActionPerformed(evt);
            }
        });

        FOVField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        FOVField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        FOVField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FOVFieldActionPerformed(evt);
            }
        });

        Off_XLabel.setBackground(new java.awt.Color(0, 238, 238));
        Off_XLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Off_XLabel.setForeground(new java.awt.Color(12, 91, 160));
        Off_XLabel.setText("OFF_X");

        SizeLabel.setBackground(new java.awt.Color(0, 238, 238));
        SizeLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SizeLabel.setForeground(new java.awt.Color(12, 91, 160));
        SizeLabel.setText("SIZE");

        SizeField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SizeField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        SizeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SizeFieldActionPerformed(evt);
            }
        });

        Off_YLabel.setBackground(new java.awt.Color(0, 238, 238));
        Off_YLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Off_YLabel.setForeground(new java.awt.Color(12, 91, 160));
        Off_YLabel.setText("OFF_Y");

        Off_XField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Off_XField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        Off_XField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Off_XFieldActionPerformed(evt);
            }
        });

        Pos_XLabel.setBackground(new java.awt.Color(0, 238, 238));
        Pos_XLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Pos_XLabel.setForeground(new java.awt.Color(12, 91, 160));
        Pos_XLabel.setText("POS_X");

        Pos_YLabel.setBackground(new java.awt.Color(0, 238, 238));
        Pos_YLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Pos_YLabel.setForeground(new java.awt.Color(12, 91, 160));
        Pos_YLabel.setText("POS_Y");

        Off_YField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Off_YField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        Off_YField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Off_YFieldActionPerformed(evt);
            }
        });

        Pos_YField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Pos_YField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        Pos_YField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pos_YFieldActionPerformed(evt);
            }
        });

        Pos_XField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Pos_XField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        Pos_XField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pos_XFieldActionPerformed(evt);
            }
        });

        UpdateDataButton.setForeground(new java.awt.Color(12, 91, 160));
        UpdateDataButton.setText("UPDATE");
        UpdateDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateDataButtonActionPerformed(evt);
            }
        });

        FOVLabel1.setBackground(new java.awt.Color(0, 238, 238));
        FOVLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        FOVLabel1.setForeground(new java.awt.Color(12, 91, 160));
        FOVLabel1.setText("FOV");

        javax.swing.GroupLayout UpdateDataPanelLayout = new javax.swing.GroupLayout(UpdateDataPanel);
        UpdateDataPanel.setLayout(UpdateDataPanelLayout);
        UpdateDataPanelLayout.setHorizontalGroup(
            UpdateDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdateDataPanelLayout.createSequentialGroup()
                .addGroup(UpdateDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UpdateDataPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(UpdateDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FOVField)
                            .addComponent(BrightnessField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(SizeField)
                            .addGroup(UpdateDataPanelLayout.createSequentialGroup()
                                .addGroup(UpdateDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Off_XLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Off_XField, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                                .addGroup(UpdateDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Off_YLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Off_YField, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UpdateDataPanelLayout.createSequentialGroup()
                                .addGroup(UpdateDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Pos_XLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BrigthnessLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SizeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Pos_XField, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(UpdateDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Pos_YField, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Pos_YLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(UpdateDataPanelLayout.createSequentialGroup()
                        .addGroup(UpdateDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(UpdateDataPanelLayout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addComponent(UpdateDataButton, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(UpdateDataPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(FOVLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        UpdateDataPanelLayout.setVerticalGroup(
            UpdateDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdateDataPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FOVLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FOVField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BrigthnessLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BrightnessField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SizeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SizeField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(UpdateDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Off_XLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Off_YLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(UpdateDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Off_XField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Off_YField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(UpdateDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pos_XLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pos_YLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(UpdateDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pos_XField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pos_YField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(UpdateDataButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        NamePanel.setBackground(new java.awt.Color(255, 255, 255));

        ClientNameLabel.setBackground(new java.awt.Color(255, 255, 255));
        ClientNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        ClientNameLabel.setForeground(new java.awt.Color(12, 91, 160));
        ClientNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout NamePanelLayout = new javax.swing.GroupLayout(NamePanel);
        NamePanel.setLayout(NamePanelLayout);
        NamePanelLayout.setHorizontalGroup(
            NamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NamePanelLayout.createSequentialGroup()
                .addComponent(ClientNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        NamePanelLayout.setVerticalGroup(
            NamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ClientNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        ShowChartButton.setBackground(new java.awt.Color(255, 255, 255));
        ShowChartButton.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        ShowChartButton.setForeground(new java.awt.Color(12, 91, 160));
        ShowChartButton.setText("Show Chart");
        ShowChartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowChartButtonActionPerformed(evt);
            }
        });

        RemoveClientButton.setBackground(new java.awt.Color(255, 255, 255));
        RemoveClientButton.setForeground(new java.awt.Color(12, 91, 160));
        RemoveClientButton.setText("Remove Client");
        RemoveClientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveClientButtonActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        BrightnessDataLabel.setBackground(new java.awt.Color(0, 238, 238));
        BrightnessDataLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BrightnessDataLabel.setForeground(new java.awt.Color(12, 91, 160));
        BrightnessDataLabel.setText("FOV:");

        VersionDataLabel.setBackground(new java.awt.Color(0, 238, 238));
        VersionDataLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        VersionDataLabel.setForeground(new java.awt.Color(12, 91, 160));
        VersionDataLabel.setText("FOV:");

        Off_YDataLabel.setBackground(new java.awt.Color(0, 238, 238));
        Off_YDataLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Off_YDataLabel.setForeground(new java.awt.Color(12, 91, 160));
        Off_YDataLabel.setText("FOV:");

        Pos_XDataLabel.setBackground(new java.awt.Color(0, 238, 238));
        Pos_XDataLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Pos_XDataLabel.setForeground(new java.awt.Color(12, 91, 160));
        Pos_XDataLabel.setText("FOV:");

        FOVDataLabel.setBackground(new java.awt.Color(0, 238, 238));
        FOVDataLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        FOVDataLabel.setForeground(new java.awt.Color(12, 91, 160));
        FOVDataLabel.setText("FOV:");

        SizeDataLabel.setBackground(new java.awt.Color(0, 238, 238));
        SizeDataLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SizeDataLabel.setForeground(new java.awt.Color(12, 91, 160));
        SizeDataLabel.setText("FOV:");

        Pos_YDataLabel.setBackground(new java.awt.Color(0, 238, 238));
        Pos_YDataLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Pos_YDataLabel.setForeground(new java.awt.Color(12, 91, 160));
        Pos_YDataLabel.setText("FOV:");

        Off_XDataLabel.setBackground(new java.awt.Color(0, 238, 238));
        Off_XDataLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Off_XDataLabel.setForeground(new java.awt.Color(12, 91, 160));
        Off_XDataLabel.setText("FOV:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(VersionDataLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BrightnessDataLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pos_XDataLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Off_XDataLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Off_YDataLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FOVDataLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SizeDataLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pos_YDataLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VersionDataLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FOVDataLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BrightnessDataLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SizeDataLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Pos_XDataLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Off_XDataLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Pos_YDataLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Off_YDataLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        Back.setBackground(new java.awt.Color(255, 255, 255));
        Back.setForeground(new java.awt.Color(12, 91, 160));
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        ChartOption.setBackground(new java.awt.Color(255, 255, 255));
        ChartOption.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ChartOption.setForeground(new java.awt.Color(12, 91, 160));
        ChartOption.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Chart", "Size", "Off_X", "Off_Y", "Pos_X", "Pos_Y" }));
        ChartOption.setMinimumSize(new java.awt.Dimension(110, 29));
        ChartOption.setPreferredSize(new java.awt.Dimension(110, 29));
        ChartOption.setSize(new java.awt.Dimension(110, 29));
        ChartOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChartOptionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NamePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ChartOption, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Back, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RemoveClientButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ShowChartButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(109, 109, 109)
                .addComponent(UpdateDataPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(NamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ShowChartButton, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(ChartOption, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RemoveClientButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(UpdateDataPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 562, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ShowChartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowChartButtonActionPerformed

         
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        String jsonStr = "";   
        String type = ChartOption.getSelectedItem().toString();
        String typeNoCaps = type.toLowerCase();
        
       if (type.equals("Select Chart")){
           JOptionPane.showMessageDialog(null, "Select a Type First");
       }else{
           try {
            String user_id = Integer.toString(client.getID());

            String link = "http://vrvision.a2hosted.com/getoffchartdata.php";
            String data = URLEncoder.encode("user_id", "UTF-8") + "="
                    + URLEncoder.encode(user_id, "UTF-8");

            URL url = new URL(link);

            URLConnection conn = url.openConnection();

            conn.setDoOutput(true);
            OutputStreamWriter wr = new OutputStreamWriter(conn.getOutputStream());

            wr.write(data);
            wr.flush();

            BufferedReader reader = new BufferedReader(new InputStreamReader(conn.getInputStream()));

            StringBuilder sb = new StringBuilder();
            String line = null;

            // Read Server Response
            while ((line = reader.readLine()) != null) {
                sb.append(line);
                break;
            }
            jsonStr = sb.toString();
        } catch (Exception e) {
        }
        
         
        try {
            JSONArray jsonarray = new JSONArray(jsonStr);
            for (int i = 0; i < jsonarray.length(); i++) {
            JSONObject jsonobject = jsonarray.getJSONObject(i);
            dataset.setValue(jsonobject.getDouble(typeNoCaps),type,jsonobject.getString("date"));

        }
        } catch (JSONException ex) {
            Logger.getLogger(ClientDataFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
       
        JFreeChart chart = ChartFactory.createLineChart(type, "Date", type, dataset);
        chart.setBackgroundPaint(Color.WHITE);
        chart.getTitle().setPaint(Color.CYAN);
        
        ChartFrame UserChart = new ChartFrame(type + " Chart for Client", chart);
        UserChart.setVisible(true);
        UserChart.setSize(600,400);
       }
      
        
        
        
    }//GEN-LAST:event_ShowChartButtonActionPerformed

    private void RemoveClientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveClientButtonActionPerformed
    String message = "";
    try {
            String client_id = Integer.toString(client.getID());

            String link = "http://vrvision.a2hosted.com/removeclient.php";
            String data = URLEncoder.encode("client_id", "UTF-8") + "="
                    + URLEncoder.encode(client_id, "UTF-8");

            URL url = new URL(link);

            URLConnection conn = url.openConnection();

            conn.setDoOutput(true);
            OutputStreamWriter wr = new OutputStreamWriter(conn.getOutputStream());

            wr.write(data);
            wr.flush();

            BufferedReader reader = new BufferedReader(new InputStreamReader(conn.getInputStream()));

            StringBuilder sb = new StringBuilder();
            String line = null;

            // Read Server Response
            while ((line = reader.readLine()) != null) {
                sb.append(line);
                break;
            }
            message = sb.toString();
        } catch (Exception e) {
        }
    
    this.setVisible(false);
    ClientViewFrame cvf = new ClientViewFrame(client.getDoctorID(), username);
    cvf.setVisible(true);
            

    }//GEN-LAST:event_RemoveClientButtonActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
      this.setVisible(false);
      ClientViewFrame cvf = new ClientViewFrame(client.getDoctorID(), username);
      cvf.setVisible(true);
    }//GEN-LAST:event_BackActionPerformed

    private void BrightnessFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrightnessFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BrightnessFieldActionPerformed

    private void FOVFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FOVFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FOVFieldActionPerformed

    private void SizeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SizeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SizeFieldActionPerformed

    private void Off_XFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Off_XFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Off_XFieldActionPerformed

    private void Off_YFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Off_YFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Off_YFieldActionPerformed

    private void Pos_YFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pos_YFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pos_YFieldActionPerformed

    private void Pos_XFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pos_XFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pos_XFieldActionPerformed

    private void UpdateDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateDataButtonActionPerformed
        String message = "";
        if ((FOVField.getText().length() > 0) && (BrightnessField.getText().length() > 0) && (SizeField.getText().length() > 0) && (Pos_XField.getText().length() > 0) && (Pos_YField.getText().length() > 0) && (Off_XField.getText().length() > 0) && (Off_YField.getText().length() > 0)){
            try {
                String user_id = Integer.toString(client.getID());
                String version_id = Integer.toString(client.getVersionID()+1);
                String fov   = FOVField.getText();
                String brightness = BrightnessField.getText();
                String size = SizeField.getText();
                String pos_x   = Pos_XField.getText();
                String pos_y = Pos_YField.getText();
                String off_x = Off_XField.getText();
                String off_y   = Off_YField.getText();


                String link = "http://vrvision.a2hosted.com/updatevalues.php";
                String data  = URLEncoder.encode("user_id", "UTF-8") + "=" +
                        URLEncoder.encode(user_id, "UTF-8");
                data += "&" + URLEncoder.encode("version_id", "UTF-8") + "=" +
                        URLEncoder.encode(version_id, "UTF-8");
                data += "&" + URLEncoder.encode("fov", "UTF-8") + "=" +
                        URLEncoder.encode(fov, "UTF-8");
                data += "&" + URLEncoder.encode("brightness", "UTF-8") + "=" +
                        URLEncoder.encode(brightness, "UTF-8");
                data += "&" + URLEncoder.encode("size", "UTF-8") + "=" +
                        URLEncoder.encode(size, "UTF-8");
                data += "&" + URLEncoder.encode("pos_x", "UTF-8") + "=" +
                        URLEncoder.encode(pos_x, "UTF-8");
                data += "&" + URLEncoder.encode("pos_y", "UTF-8") + "=" +
                        URLEncoder.encode(pos_y, "UTF-8");
                data += "&" + URLEncoder.encode("off_x", "UTF-8") + "=" +
                        URLEncoder.encode(off_x, "UTF-8");
                data += "&" + URLEncoder.encode("off_y", "UTF-8") + "=" +
                        URLEncoder.encode(off_y, "UTF-8");


                URL url = new URL(link);

                URLConnection conn = url.openConnection();


                conn.setDoOutput(true);
                OutputStreamWriter wr = new OutputStreamWriter(conn.getOutputStream());

                wr.write( data );
                wr.flush();

                BufferedReader reader = new BufferedReader(new
                        InputStreamReader(conn.getInputStream()));

                StringBuilder sb = new StringBuilder();
                String line = null;

                // Read Server Response
                while((line = reader.readLine()) != null) {
                    sb.append(line);
                    break;
                }
                message = sb.toString();
                
            } catch (Exception e) {
            }
        }
        else{
            message = "Make sure all fields are filled";
        }
        
        JOptionPane.showMessageDialog(null, message);
    }//GEN-LAST:event_UpdateDataButtonActionPerformed

    private void ChartOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChartOptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChartOptionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientDataFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientDataFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientDataFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientDataFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JLabel BrightnessDataLabel;
    private javax.swing.JTextField BrightnessField;
    private javax.swing.JLabel BrigthnessLabel;
    private javax.swing.JComboBox<String> ChartOption;
    private javax.swing.JLabel ClientNameLabel;
    private javax.swing.JLabel FOVDataLabel;
    private javax.swing.JTextField FOVField;
    private javax.swing.JLabel FOVLabel1;
    private javax.swing.JPanel NamePanel;
    private javax.swing.JLabel Off_XDataLabel;
    private javax.swing.JTextField Off_XField;
    private javax.swing.JLabel Off_XLabel;
    private javax.swing.JLabel Off_YDataLabel;
    private javax.swing.JTextField Off_YField;
    private javax.swing.JLabel Off_YLabel;
    private javax.swing.JLabel Pos_XDataLabel;
    private javax.swing.JTextField Pos_XField;
    private javax.swing.JLabel Pos_XLabel;
    private javax.swing.JLabel Pos_YDataLabel;
    private javax.swing.JTextField Pos_YField;
    private javax.swing.JLabel Pos_YLabel;
    private javax.swing.JButton RemoveClientButton;
    private javax.swing.JButton ShowChartButton;
    private javax.swing.JLabel SizeDataLabel;
    private javax.swing.JTextField SizeField;
    private javax.swing.JLabel SizeLabel;
    private javax.swing.JButton UpdateDataButton;
    private javax.swing.JPanel UpdateDataPanel;
    private javax.swing.JLabel VersionDataLabel;
    private javax.swing.JPanel jPanel1;
    private keeptoo.KGradientPanel kGradientPanel1;
    // End of variables declaration//GEN-END:variables
}
